server:
  port: 8080

spring:
  application:
    name: configClient
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8887

# acuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh

